Repository Tilk1/ScrabblleUNLPAgusSanti, pull requests merged in 2020-08, with the labels that each got.

#22 Bolsa sin fichas termina el juego
  scrabble/ScrabbleAR.py
  scrabble/compu.py
  scrabble/configuraciones.py
  scrabble/funcionesFichas.py
  scrabble/test.py
Labels: enhancement

#37 Correcciones gaspar
  imagenes/palabra.png
  scrabble/ScrabbleAR.py
  scrabble/compu.py
  scrabble/funciones.py
Labels: cambios esteticos, fix

#36 Fix Timer
  scrabble/ScrabbleAR.py
Labels: fix
